version: '3.8'

services:
  user_api:
    build:
      context: ./user_api
      dockerfile: Dockerfile
    ports:
      - "${USER_API_PORT}:3001"
    environment:
      - PORT=${USER_API_PORT}
      - DB_URI=${USER_DB_URI}
      - WASTE_API_URL=http://waste_api:3002  # Add an environment variable for waste_api URL
    depends_on:
      - mongodb
      - waste_api  # Ensure waste_api starts before user_api

  waste_api:
    build:
      context: ./waste_api
      dockerfile: Dockerfile
    ports:
      - "${WASTE_API_PORT}:3002"
    environment:
      - PORT=${WASTE_API_PORT}
      - DB_URI=${WASTE_DB_URI}
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin